<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__icon-paperplane</name>
   <tag></tag>
   <elementGuidId>ebdf8cd6-3568-4514-b624-a06d8b9e8f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-paperplane</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Submit']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5bd7ed0a-7c3c-44e9-9f74-adaf257171a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-paperplane</value>
      <webElementGuid>7eb54894-540e-4784-b348-e1719b4dc8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Submit&quot;)/i[@class=&quot;icon-paperplane&quot;]</value>
      <webElementGuid>12e9e445-0aca-46a1-836d-77856e64072b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Submit']/i</value>
      <webElementGuid>54a59d26-a377-400c-ae22-3434b1a0a7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/i</value>
      <webElementGuid>d276ea3f-f2bb-42cb-b90b-5be183a05763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
