<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>5edef71e-7cc9-4a5d-84e9-c16fe7c51375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-ddlMonths-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ddlMonths-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e0859e3-d450-4bd5-93e6-0f92fe206c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>670ab284-2cd1-4e5e-89b5-6da79e740b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ddlMonths-container</value>
      <webElementGuid>ebbcc92d-1aee-4ad1-b39e-d62fadce40b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>47e1c0e4-40d9-41c9-b8ba-febf0ed51edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2bdf2cc8-b4b0-4966-a580-644985fc025f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اختر الشهر</value>
      <webElementGuid>90c0aac8-3993-4526-925b-75c950e2d7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ddlMonths-container&quot;)</value>
      <webElementGuid>e4a4d345-2da4-4ad9-ac4e-91fb189f8363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ddlMonths-container']</value>
      <webElementGuid>6b7f2b40-e390-4a63-a9a9-ecc5a9248d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rowMonth']/span/span/span/span</value>
      <webElementGuid>7a001c5c-9550-4d0b-bef6-6994ee1275f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الأشهر'])[1]/following::span[4]</value>
      <webElementGuid>9bb08a45-a4f7-4da7-9e69-f8aabadfe4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السنوات'])[1]/following::span[11]</value>
      <webElementGuid>50da964f-a30f-40b2-ad4a-6a16bc9e2cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الفترات'])[1]/preceding::span[5]</value>
      <webElementGuid>59557a85-09b4-4ffd-9f44-14af68acea0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span/span/span</value>
      <webElementGuid>dc2fc777-2af6-4b66-8376-6f75aa75bc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ddlMonths-container' and (text() = 'اختر الشهر' or . = 'اختر الشهر')]</value>
      <webElementGuid>a3bb27f2-e42a-46fe-816f-557d2c3b925d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
