<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>19377a5d-c1e0-4cd8-8f3f-67b19a527424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-ddlYear-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-ddlYear-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>537ec1da-0b6c-47ea-a2ae-a2be1adffb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>b6469320-db44-4ce1-9d02-410c996226b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-ddlYear-container</value>
      <webElementGuid>da4a872c-fbee-4c91-b2ef-7323d54351c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6b0c77f0-117c-4e1d-aa02-8308d0e6dc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4af29e2a-79a7-4cc3-8081-defb25398d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اختر السنة</value>
      <webElementGuid>928ce25a-a931-493d-8df1-33c4010ffd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-ddlYear-container&quot;)</value>
      <webElementGuid>9e02f1cd-2d12-41c3-aa70-9d12c973720a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-ddlYear-container']</value>
      <webElementGuid>c1f0ed5d-44b3-4a94-a6c9-2852e114571f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rowYear']/span/span/span/span</value>
      <webElementGuid>9bd1c1fd-9bae-49c3-a48c-c2aa198c1e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='السنوات'])[1]/following::span[4]</value>
      <webElementGuid>53909fe0-ef2e-4b4e-a10f-65c56d6b53ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='معلومات شهادة الراتب'])[1]/following::span[4]</value>
      <webElementGuid>9f03865f-e86d-4b4f-b39a-6eda62c3d0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الأشهر'])[1]/preceding::span[5]</value>
      <webElementGuid>ac1fa4d6-dab6-4982-a763-a4a6fc89b396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>df4f9a6f-58e3-4ad7-ad93-c98eb7f66f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-ddlYear-container' and (text() = 'اختر السنة' or . = 'اختر السنة')]</value>
      <webElementGuid>46433da0-5da9-491c-b03f-12fc3a0a5390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
